# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgame_state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import hero_pb2 as hero__pb2
from . import scene_pb2 as scene__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgame_state.proto',
  package='sgame_state',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11sgame_state.proto\x12\x0bsgame_state\x1a\x0c\x63ommon.proto\x1a\nhero.proto\x1a\x0bscene.proto\"\xec\x01\n\nFrameState\x12\x0f\n\x07\x66rameNo\x18\x01 \x02(\x05\x12+\n\x0bhero_states\x18\x02 \x03(\x0b\x32\x16.sgame_state.HeroState\x12+\n\nnpc_states\x18\x03 \x03(\x0b\x32\x17.sgame_state.ActorState\x12$\n\x07\x62ullets\x18\x04 \x03(\x0b\x32\x13.sgame_state.Bullet\x12 \n\x05\x63\x61kes\x18\x05 \x03(\x0b\x32\x11.sgame_state.Cake\x12+\n\x0b\x65quip_infos\x18\x06 \x03(\x0b\x32\x16.sgame_state.EquipInfo\"5\n\nFrameSlice\x12\'\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x17.sgame_state.FrameState\"G\n\x0c\x43\x61mpStatInfo\x12\x0c\n\x04\x63\x61mp\x18\x01 \x02(\x05\x12\r\n\x05score\x18\x02 \x02(\x05\x12\r\n\x05money\x18\x03 \x02(\x05\x12\x0b\n\x03\x65xp\x18\x04 \x02(\x05\"\xcb\x02\n\x0cHeroStatInfo\x12\x12\n\nruntime_id\x18\x01 \x02(\x05\x12\r\n\x05score\x18\x02 \x02(\x05\x12\r\n\x05money\x18\x03 \x02(\x05\x12\x1d\n\x15totalHurtToHeroOrigin\x18\x04 \x01(\x05\x12\x1f\n\x17totalBeHurtByHeroOrigin\x18\x05 \x01(\x05\x12\x17\n\x0f\x64\x65stroyTowerCnt\x18\x06 \x01(\x05\x12\x16\n\x0ekillSoidierCnt\x18\x07 \x01(\x05\x12\x16\n\x0eKillMonsterCnt\x18\x08 \x01(\x05\x12\x1b\n\x13KillLittleDragonCnt\x18\t \x01(\x05\x12\x1d\n\x15Hero1KillBigDragonCnt\x18\n \x01(\x05\x12\x17\n\x0fSelfKillDarkCnt\x18\x0b \x01(\x05\x12\x14\n\x0cTotalRedBuff\x18\x0c \x01(\x05\x12\x15\n\rTotalBlueBuff\x18\r \x01(\x05\"r\n\nCloseState\x12\x31\n\x0e\x63\x61mp_stat_info\x18\x01 \x03(\x0b\x32\x19.sgame_state.CampStatInfo\x12\x31\n\x0ehero_stat_info\x18\x02 \x03(\x0b\x32\x19.sgame_state.HeroStatInfo\"G\n\tEquipInfo\x12\x10\n\x08\x65quip_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65quip_price\x18\x02 \x01(\x05\x12\x13\n\x0b\x65quip_atoms\x18\x03 \x03(\x05\"c\n\x10MonsterSpawnInfo\x12\x12\n\nmonster_id\x18\x01 \x01(\x05\x12\x13\n\x0bspawn_timer\x18\x02 \x01(\x05\x12\x12\n\nborn_pos_x\x18\x03 \x01(\x05\x12\x12\n\nborn_pos_z\x18\x04 \x01(\x05'
  ,
  dependencies=[common__pb2.DESCRIPTOR,hero__pb2.DESCRIPTOR,scene__pb2.DESCRIPTOR,])




_FRAMESTATE = _descriptor.Descriptor(
  name='FrameState',
  full_name='sgame_state.FrameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameNo', full_name='sgame_state.FrameState.frameNo', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hero_states', full_name='sgame_state.FrameState.hero_states', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='npc_states', full_name='sgame_state.FrameState.npc_states', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bullets', full_name='sgame_state.FrameState.bullets', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cakes', full_name='sgame_state.FrameState.cakes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equip_infos', full_name='sgame_state.FrameState.equip_infos', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=310,
)


_FRAMESLICE = _descriptor.Descriptor(
  name='FrameSlice',
  full_name='sgame_state.FrameSlice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='sgame_state.FrameSlice.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=365,
)


_CAMPSTATINFO = _descriptor.Descriptor(
  name='CampStatInfo',
  full_name='sgame_state.CampStatInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camp', full_name='sgame_state.CampStatInfo.camp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='sgame_state.CampStatInfo.score', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='sgame_state.CampStatInfo.money', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exp', full_name='sgame_state.CampStatInfo.exp', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=438,
)


_HEROSTATINFO = _descriptor.Descriptor(
  name='HeroStatInfo',
  full_name='sgame_state.HeroStatInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='runtime_id', full_name='sgame_state.HeroStatInfo.runtime_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='sgame_state.HeroStatInfo.score', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='sgame_state.HeroStatInfo.money', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalHurtToHeroOrigin', full_name='sgame_state.HeroStatInfo.totalHurtToHeroOrigin', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalBeHurtByHeroOrigin', full_name='sgame_state.HeroStatInfo.totalBeHurtByHeroOrigin', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destroyTowerCnt', full_name='sgame_state.HeroStatInfo.destroyTowerCnt', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='killSoidierCnt', full_name='sgame_state.HeroStatInfo.killSoidierCnt', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KillMonsterCnt', full_name='sgame_state.HeroStatInfo.KillMonsterCnt', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='KillLittleDragonCnt', full_name='sgame_state.HeroStatInfo.KillLittleDragonCnt', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Hero1KillBigDragonCnt', full_name='sgame_state.HeroStatInfo.Hero1KillBigDragonCnt', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SelfKillDarkCnt', full_name='sgame_state.HeroStatInfo.SelfKillDarkCnt', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalRedBuff', full_name='sgame_state.HeroStatInfo.TotalRedBuff', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TotalBlueBuff', full_name='sgame_state.HeroStatInfo.TotalBlueBuff', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=772,
)


_CLOSESTATE = _descriptor.Descriptor(
  name='CloseState',
  full_name='sgame_state.CloseState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camp_stat_info', full_name='sgame_state.CloseState.camp_stat_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hero_stat_info', full_name='sgame_state.CloseState.hero_stat_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=774,
  serialized_end=888,
)


_EQUIPINFO = _descriptor.Descriptor(
  name='EquipInfo',
  full_name='sgame_state.EquipInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='equip_id', full_name='sgame_state.EquipInfo.equip_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equip_price', full_name='sgame_state.EquipInfo.equip_price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equip_atoms', full_name='sgame_state.EquipInfo.equip_atoms', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=890,
  serialized_end=961,
)


_MONSTERSPAWNINFO = _descriptor.Descriptor(
  name='MonsterSpawnInfo',
  full_name='sgame_state.MonsterSpawnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster_id', full_name='sgame_state.MonsterSpawnInfo.monster_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spawn_timer', full_name='sgame_state.MonsterSpawnInfo.spawn_timer', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='born_pos_x', full_name='sgame_state.MonsterSpawnInfo.born_pos_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='born_pos_z', full_name='sgame_state.MonsterSpawnInfo.born_pos_z', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=963,
  serialized_end=1062,
)

_FRAMESTATE.fields_by_name['hero_states'].message_type = hero__pb2._HEROSTATE
_FRAMESTATE.fields_by_name['npc_states'].message_type = common__pb2._ACTORSTATE
_FRAMESTATE.fields_by_name['bullets'].message_type = scene__pb2._BULLET
_FRAMESTATE.fields_by_name['cakes'].message_type = scene__pb2._CAKE
_FRAMESTATE.fields_by_name['equip_infos'].message_type = _EQUIPINFO
_FRAMESLICE.fields_by_name['frames'].message_type = _FRAMESTATE
_CLOSESTATE.fields_by_name['camp_stat_info'].message_type = _CAMPSTATINFO
_CLOSESTATE.fields_by_name['hero_stat_info'].message_type = _HEROSTATINFO
DESCRIPTOR.message_types_by_name['FrameState'] = _FRAMESTATE
DESCRIPTOR.message_types_by_name['FrameSlice'] = _FRAMESLICE
DESCRIPTOR.message_types_by_name['CampStatInfo'] = _CAMPSTATINFO
DESCRIPTOR.message_types_by_name['HeroStatInfo'] = _HEROSTATINFO
DESCRIPTOR.message_types_by_name['CloseState'] = _CLOSESTATE
DESCRIPTOR.message_types_by_name['EquipInfo'] = _EQUIPINFO
DESCRIPTOR.message_types_by_name['MonsterSpawnInfo'] = _MONSTERSPAWNINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FrameState = _reflection.GeneratedProtocolMessageType('FrameState', (_message.Message,), {
  'DESCRIPTOR' : _FRAMESTATE,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.FrameState)
  })
_sym_db.RegisterMessage(FrameState)

FrameSlice = _reflection.GeneratedProtocolMessageType('FrameSlice', (_message.Message,), {
  'DESCRIPTOR' : _FRAMESLICE,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.FrameSlice)
  })
_sym_db.RegisterMessage(FrameSlice)

CampStatInfo = _reflection.GeneratedProtocolMessageType('CampStatInfo', (_message.Message,), {
  'DESCRIPTOR' : _CAMPSTATINFO,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.CampStatInfo)
  })
_sym_db.RegisterMessage(CampStatInfo)

HeroStatInfo = _reflection.GeneratedProtocolMessageType('HeroStatInfo', (_message.Message,), {
  'DESCRIPTOR' : _HEROSTATINFO,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.HeroStatInfo)
  })
_sym_db.RegisterMessage(HeroStatInfo)

CloseState = _reflection.GeneratedProtocolMessageType('CloseState', (_message.Message,), {
  'DESCRIPTOR' : _CLOSESTATE,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.CloseState)
  })
_sym_db.RegisterMessage(CloseState)

EquipInfo = _reflection.GeneratedProtocolMessageType('EquipInfo', (_message.Message,), {
  'DESCRIPTOR' : _EQUIPINFO,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.EquipInfo)
  })
_sym_db.RegisterMessage(EquipInfo)

MonsterSpawnInfo = _reflection.GeneratedProtocolMessageType('MonsterSpawnInfo', (_message.Message,), {
  'DESCRIPTOR' : _MONSTERSPAWNINFO,
  '__module__' : 'sgame_state_pb2'
  # @@protoc_insertion_point(class_scope:sgame_state.MonsterSpawnInfo)
  })
_sym_db.RegisterMessage(MonsterSpawnInfo)


# @@protoc_insertion_point(module_scope)
