# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_king/sgame_ai_server.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .. import command_pb2 as command__pb2
from .. import sgame_state_pb2 as sgame__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_king/sgame_ai_server.proto',
  package='kaiwu_aisvr',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n proto_king/sgame_ai_server.proto\x12\x0bkaiwu_aisvr\x1a\rcommand.proto\x1a\x11sgame_state.proto\"I\n\rAICommandInfo\x12\x11\n\tplayer_id\x18\x01 \x02(\x05\x12%\n\x08\x63md_info\x18\x02 \x01(\x0b\x32\x13.sgame_state.CmdPkg\"\xa3\x01\n\x0f\x41IServerRequest\x12\x10\n\x08sgame_id\x18\x01 \x02(\t\x12\x10\n\x08\x66rame_no\x18\x02 \x02(\x05\x12\x10\n\x08gameover\x18\x03 \x01(\x08\x12,\n\x08\x63md_list\x18\x04 \x03(\x0b\x32\x1a.kaiwu_aisvr.AICommandInfo\x12,\n\x0b\x66rame_state\x18\x05 \x01(\x0b\x32\x17.sgame_state.FrameState\"h\n\tSingleReq\x12,\n\x06\x61i_req\x18\x01 \x02(\x0b\x32\x1c.kaiwu_aisvr.AIServerRequest\x12\x10\n\x08req_type\x18\x02 \x02(\x05\x12\x0e\n\x06seq_no\x18\x03 \x02(\x05\x12\x0b\n\x03pid\x18\x04 \x02(\x05\"\\\n\x10\x41IServerResponse\x12,\n\x08\x63md_list\x18\x01 \x03(\x0b\x32\x1a.kaiwu_aisvr.AICommandInfo\x12\x1a\n\x12gameover_ai_server\x18\x02 \x01(\x05\"\x1d\n\nPlayerInfo\x12\x0f\n\x07hero_id\x18\x01 \x02(\x05\"c\n\x08GameInfo\x12,\n\x0bplayer_info\x18\x01 \x03(\x0b\x32\x17.kaiwu_aisvr.PlayerInfo\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\"\xbc\x01\n\x14KaiwuAIServerRequest\x12(\n\x08req_list\x18\x01 \x03(\x0b\x32\x16.kaiwu_aisvr.SingleReq\x12\x12\n\nplayer_num\x18\x02 \x01(\x05\x12\x0f\n\x07game_id\x18\x03 \x02(\t\x12+\n\x08msg_type\x18\x04 \x02(\x0e\x32\x19.kaiwu_aisvr.KaiWuMsgType\x12(\n\tgame_info\x18\x05 \x01(\x0b\x32\x15.kaiwu_aisvr.GameInfo\"U\n\x15KaiwuAIServerResponse\x12.\n\x07rsp_pbs\x18\x01 \x03(\x0b\x32\x1d.kaiwu_aisvr.AIServerResponse\x12\x0c\n\x04\x63ode\x18\x02 \x02(\x05*A\n\x0cKaiWuMsgType\x12\r\n\tE_UNKNOWN\x10\x00\x12\n\n\x06\x45_INIT\x10\x01\x12\x0b\n\x07\x45_FRAME\x10\x02\x12\t\n\x05\x45_END\x10\x03'
  ,
  dependencies=[command__pb2.DESCRIPTOR,sgame__state__pb2.DESCRIPTOR,])

_KAIWUMSGTYPE = _descriptor.EnumDescriptor(
  name='KaiWuMsgType',
  full_name='kaiwu_aisvr.KaiWuMsgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='E_INIT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='E_FRAME', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='E_END', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=934,
  serialized_end=999,
)
_sym_db.RegisterEnumDescriptor(_KAIWUMSGTYPE)

KaiWuMsgType = enum_type_wrapper.EnumTypeWrapper(_KAIWUMSGTYPE)
E_UNKNOWN = 0
E_INIT = 1
E_FRAME = 2
E_END = 3



_AICOMMANDINFO = _descriptor.Descriptor(
  name='AICommandInfo',
  full_name='kaiwu_aisvr.AICommandInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='kaiwu_aisvr.AICommandInfo.player_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd_info', full_name='kaiwu_aisvr.AICommandInfo.cmd_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=156,
)


_AISERVERREQUEST = _descriptor.Descriptor(
  name='AIServerRequest',
  full_name='kaiwu_aisvr.AIServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sgame_id', full_name='kaiwu_aisvr.AIServerRequest.sgame_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_no', full_name='kaiwu_aisvr.AIServerRequest.frame_no', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameover', full_name='kaiwu_aisvr.AIServerRequest.gameover', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd_list', full_name='kaiwu_aisvr.AIServerRequest.cmd_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_state', full_name='kaiwu_aisvr.AIServerRequest.frame_state', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=322,
)


_SINGLEREQ = _descriptor.Descriptor(
  name='SingleReq',
  full_name='kaiwu_aisvr.SingleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ai_req', full_name='kaiwu_aisvr.SingleReq.ai_req', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req_type', full_name='kaiwu_aisvr.SingleReq.req_type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seq_no', full_name='kaiwu_aisvr.SingleReq.seq_no', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pid', full_name='kaiwu_aisvr.SingleReq.pid', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=428,
)


_AISERVERRESPONSE = _descriptor.Descriptor(
  name='AIServerResponse',
  full_name='kaiwu_aisvr.AIServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_list', full_name='kaiwu_aisvr.AIServerResponse.cmd_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameover_ai_server', full_name='kaiwu_aisvr.AIServerResponse.gameover_ai_server', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=522,
)


_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='kaiwu_aisvr.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero_id', full_name='kaiwu_aisvr.PlayerInfo.hero_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=553,
)


_GAMEINFO = _descriptor.Descriptor(
  name='GameInfo',
  full_name='kaiwu_aisvr.GameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_info', full_name='kaiwu_aisvr.GameInfo.player_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='kaiwu_aisvr.GameInfo.client_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_version', full_name='kaiwu_aisvr.GameInfo.client_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=654,
)


_KAIWUAISERVERREQUEST = _descriptor.Descriptor(
  name='KaiwuAIServerRequest',
  full_name='kaiwu_aisvr.KaiwuAIServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_list', full_name='kaiwu_aisvr.KaiwuAIServerRequest.req_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_num', full_name='kaiwu_aisvr.KaiwuAIServerRequest.player_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='kaiwu_aisvr.KaiwuAIServerRequest.game_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='kaiwu_aisvr.KaiwuAIServerRequest.msg_type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_info', full_name='kaiwu_aisvr.KaiwuAIServerRequest.game_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=845,
)


_KAIWUAISERVERRESPONSE = _descriptor.Descriptor(
  name='KaiwuAIServerResponse',
  full_name='kaiwu_aisvr.KaiwuAIServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rsp_pbs', full_name='kaiwu_aisvr.KaiwuAIServerResponse.rsp_pbs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='kaiwu_aisvr.KaiwuAIServerResponse.code', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=847,
  serialized_end=932,
)

_AICOMMANDINFO.fields_by_name['cmd_info'].message_type = command__pb2._CMDPKG
_AISERVERREQUEST.fields_by_name['cmd_list'].message_type = _AICOMMANDINFO
_AISERVERREQUEST.fields_by_name['frame_state'].message_type = sgame__state__pb2._FRAMESTATE
_SINGLEREQ.fields_by_name['ai_req'].message_type = _AISERVERREQUEST
_AISERVERRESPONSE.fields_by_name['cmd_list'].message_type = _AICOMMANDINFO
_GAMEINFO.fields_by_name['player_info'].message_type = _PLAYERINFO
_KAIWUAISERVERREQUEST.fields_by_name['req_list'].message_type = _SINGLEREQ
_KAIWUAISERVERREQUEST.fields_by_name['msg_type'].enum_type = _KAIWUMSGTYPE
_KAIWUAISERVERREQUEST.fields_by_name['game_info'].message_type = _GAMEINFO
_KAIWUAISERVERRESPONSE.fields_by_name['rsp_pbs'].message_type = _AISERVERRESPONSE
DESCRIPTOR.message_types_by_name['AICommandInfo'] = _AICOMMANDINFO
DESCRIPTOR.message_types_by_name['AIServerRequest'] = _AISERVERREQUEST
DESCRIPTOR.message_types_by_name['SingleReq'] = _SINGLEREQ
DESCRIPTOR.message_types_by_name['AIServerResponse'] = _AISERVERRESPONSE
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['GameInfo'] = _GAMEINFO
DESCRIPTOR.message_types_by_name['KaiwuAIServerRequest'] = _KAIWUAISERVERREQUEST
DESCRIPTOR.message_types_by_name['KaiwuAIServerResponse'] = _KAIWUAISERVERRESPONSE
DESCRIPTOR.enum_types_by_name['KaiWuMsgType'] = _KAIWUMSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AICommandInfo = _reflection.GeneratedProtocolMessageType('AICommandInfo', (_message.Message,), {
  'DESCRIPTOR' : _AICOMMANDINFO,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.AICommandInfo)
  })
_sym_db.RegisterMessage(AICommandInfo)

AIServerRequest = _reflection.GeneratedProtocolMessageType('AIServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _AISERVERREQUEST,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.AIServerRequest)
  })
_sym_db.RegisterMessage(AIServerRequest)

SingleReq = _reflection.GeneratedProtocolMessageType('SingleReq', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEREQ,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.SingleReq)
  })
_sym_db.RegisterMessage(SingleReq)

AIServerResponse = _reflection.GeneratedProtocolMessageType('AIServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _AISERVERRESPONSE,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.AIServerResponse)
  })
_sym_db.RegisterMessage(AIServerResponse)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERINFO,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.PlayerInfo)
  })
_sym_db.RegisterMessage(PlayerInfo)

GameInfo = _reflection.GeneratedProtocolMessageType('GameInfo', (_message.Message,), {
  'DESCRIPTOR' : _GAMEINFO,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.GameInfo)
  })
_sym_db.RegisterMessage(GameInfo)

KaiwuAIServerRequest = _reflection.GeneratedProtocolMessageType('KaiwuAIServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _KAIWUAISERVERREQUEST,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.KaiwuAIServerRequest)
  })
_sym_db.RegisterMessage(KaiwuAIServerRequest)

KaiwuAIServerResponse = _reflection.GeneratedProtocolMessageType('KaiwuAIServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _KAIWUAISERVERRESPONSE,
  '__module__' : 'proto_king.sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.KaiwuAIServerResponse)
  })
_sym_db.RegisterMessage(KaiwuAIServerResponse)


# @@protoc_insertion_point(module_scope)
